"""empty message

Revision ID: 56da73ac666c
Revises: 88272b0368b6
Create Date: 2018-02-15 15:55:22.935072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56da73ac666c'
down_revision = '88272b0368b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response')
    # ### end Alembic commands ###
