"""empty message

Revision ID: 88272b0368b6
Revises: 
Create Date: 2018-02-13 11:56:37.368186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88272b0368b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'messages', 'users', ['author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
